version: '3'

# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e  -p 5432:5432 bitnami/postgresql:latest

services: 
  api-solid-pg:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker 
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid